miniblog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('about/',views.about ,name="about"),
    path("contact/",views.contact , name='contact') ,
    path("dashborad/",views.dashborad , name='dashborad') ,
    path("signup/",views.usersignup , name='signup') ,
    path("login/",views.userlogin, name='login') ,
    path("logout/",views.userlogout, name='logout') ,
    path('addpost/',views.addpost, name='addpost'),
    path('updatepost/<int:id>/',views.updatepost, name='updatepost'),
    path('deletepost/<int:id>/',views.deletepost, name='deletepost'),

]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=150)
    desc=models.TextField()

blog/forms.py
from django import forms
from django.contrib.auth .forms  import UserCreationForm,AuthenticationForm, UsernameField
from  django.contrib.auth.models import User
from django.db import models
from django.db.models.base import Model
from django.forms import fields
from django.forms import widgets
from django.forms.widgets import PasswordInput, Widget
from django.utils.translation import gettext, gettext_lazy as _
from.models import Post

class SignUpForm(UserCreationForm):
        password1=forms.CharField(label='Password', widget=PasswordInput(attrs={'class':'form-control'}))
        password2=forms.CharField(label='Confirm Password(again)',widget=PasswordInput(attrs={'class':'form-control'})) # hite name chaneg kel pass cha nav lebel gheun  widget gheun dot dto sathi passinput dila
        class Meta:
                model=User
                fields=['username', 'first_name', 'last_name', 'email']
                labels={'first_name':'Frist Name', 'last_name':'Last Name' ,'email':'Email'} # label gheun tya filedch name mdhe change kela
                widgets={'username':forms.TextInput(attrs={'class':'form-control'}),
                        'first_name':forms.TextInput(attrs={'class':'form-control'}),  
                        'last_name':forms.TextInput(attrs={'class':'form-control'}),  
                        'email':forms.EmailInput(attrs={'class':'form-control'}),     # bootstrap cha class lavnya satho widget cha use krun attrs cha usr krunb form control lavla
                
                }
class LoginForm(AuthenticationForm):
        username=UsernameField(widget=forms.TextInput(attrs={'autofocus':True,'class':'form-control'}))
        password=forms.CharField(label=_("Password"),strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password','class':'form-control'}))


class PostForm(forms.ModelForm):
        class Meta:
            model=Post
            fields=['title','desc']
            labels={'title':'Title','desc':'Description'}
            widgets={'title':forms.TextInput(attrs={'class':'form-control'}),
                        'desc':forms.Textarea(attrs={'class':'form-control'}),
                }

blog/views.py
from django.contrib.auth import forms
from django.shortcuts import render,HttpResponseRedirect
from .forms import SignUpForm, LoginForm, PostForm
from django.contrib import messages
from django.contrib.auth import authenticate ,login,logout
from.models import Post
from django.contrib.auth.models import Group
# Create your views here.
def home(request):
    posts=Post.objects.all()
    return render(request,'blog/home.html',{'posts':posts})

def about(request):
    return render(request,'blog/about.html')

def contact(request):
    return render(request,"blog/contact.html")


def dashborad(request):
    if request.user.is_authenticated:
       posts=Post.objects.all()
       user=request.user
       full_name=user.get_full_name()
       gps=user.groups.all()
       return render(request,"blog/dashborad.html",{'posts':posts ,'full_name':full_name ,'groups':gps})
    else:
        return HttpResponseRedirect('/login/')

def  userlogout(request):
    logout(request)
    return HttpResponseRedirect('/')


def usersignup(request):
    if request.method=="POST":
     form=SignUpForm(request.POST)
     if form.is_valid():
      messages.success(request,"Congratulations !!  You have become an author.")
      user=form.save()
      group=Group.objects.get(name="Author")
      user.groups.add(group)
    else:
      form=SignUpForm()
    return render(request,"blog/signup.html",{'form':form})


def userlogin(request):
    if not  request.user.is_authenticated:
        if request.method=="POST":   #data post he to use 
            form=LoginForm(request=request, data=request.POST)
            if form.is_valid():
                uname=form.cleaned_data['username']
                upass=form.cleaned_data['password']
                user=authenticate(username=uname,password=upass) # agar auth hota to to e user object de ga
                if user is not None:   # agar not none he to user ko login krne ki permision dena
                    login(request,user)
                    messages.success(request,"logged in successfully..!!")
                    return HttpResponseRedirect('/dashborad/')
        else:    #get me ata he to user o blank form d
           form=LoginForm()
        return render(request,"blog/login.html",{'form':form})
    else:
        return HttpResponseRedirect('/dashborad/')


  
def addpost(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form=PostForm(request.POST)
            if form.is_valid():
             title=form.cleaned_data['title']
             desc=form.cleaned_data['desc']
             pst=Post(title=title,desc=desc)
             messages.success(request,"Post is Add.....!!!")
             pst.save()
             form = PostForm()
        else:
            form=PostForm()
        return render(request,'blog/addpost.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/')
            

            

def updatepost(request ,id):
    if request.user.is_authenticated:
        if request.method =="POST":
            pi=Post.objects.get(pk=id)
            form=PostForm(request.POST, instance=pi)
            if form.is_valid():
              messages.success(request,"Post is Updated.....!!!")
              form.save()
        else:
            pi=Post.objects.get(pk=id)
            form=PostForm(instance=pi)
        return render(request,'blog/updatepost.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/') 
    

      

def deletepost(request ,id):
    if request.user.is_authenticated:
        if request.method =="POST":
          pi=Post.objects.get(pk=id)
          messages.success(request,"Post is Deleted.....!!!")
          pi.delete()
          return HttpResponseRedirect('/dashborad/')
    else:
        return HttpResponseRedirect('/login/')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
 
<div class="col-sm-10">
    <h3 class="text-white my-5">About Page</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita 
        tempora cum consequuntur sunt omnis
        ipsam adipisci laudantium dolore.alias in. 
        impedit amet quae voluptate eius officia?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet consequuntur ut, officiis placeat fugiat praesentium, in sapiente corrupti hic nemo enim consectetur nulla exercitationem minus laboriosam? Rerum eos laborum aspernatur labore doloribus asperiores ipsa amet, ex neque assumenda tempora saepe quae voluptatem
         velit impedit cupiditate officiis exercitationem accusamus doloremque? Earum.</p>
</div>

{% endblock content %}

blog/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
 <div class="col-sm-10"> 
     
    {% if messages %}
    {% for message in messages %}
     <p {% if message.tags%} class="alert alert-{{message.tags}} my-5" {% endif %}>{{message}}</p>
    {% endfor %}
    {% endif %}

   <h1 class="text-white my-5">Dashborad/ Add Post</h1>
   <form action="" method="post" novalidate>
       {% csrf_token %}
       {{form.as_p}}
       <input type="submit" value="Add" class="btn btn-success">
       <a href="{% url 'dashborad' %}" class="btn btn-danger">Cancel</a>
   </form>
 </div>

{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <title>Document</title>
</head>
<body class="bg-">
    <div class="container-fluid bg-dark">
      {% include 'blog/navbar.html' %}

    </div>
    <div class="container">
         <div class="row">
            <div class="col-sm-12">
             {% block msg %}
             {% endblock msg %}
            </div>
         </div>
        <div class="row">
           {% block side %}
       
           {% endblock side %}

           {% block content %}
           {% endblock content %}

        </div>
    </div>
    
    <script src="{%  static 'blog/js/jquery.js' %}"></script>
    <script src="{%  static 'blog/js/popper.js' %}"></script>
    <script src="{%  static 'blog/js/bootstrap.js' %}"></script>
</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
 
<div class="col-sm-10">
    <h3 class="text-white my-5">Contact Page</h3>
 <form>
     <div class="form-row">
         <div class="form-group col-md-6">
            <label for="inputname">Name</label>
            <input type="text" class="form-control" id="inputname">
         </div>
         <div class="form-group col-md-6">
            <label for="inputname">Email</label>
            <input type="text" class="form-control" id="inputname">
         </div>
     </div>
     <div class="form-group">
        <label for="inputaddress">Address</label>
        <input type="text" class="form-control" id="inputaddress">
     </div>
     <div class="form-group ">
        <label for="message">Message</label>
        <textarea class="form-control" id="message" rows="3"></textarea>
     </div>
     <div>
         <button  type="button" class="btn btn-primary">Send</button>
     </div>
 </form>
   
</div>

{% endblock content %}

blog/templates/blog/dashborad.html
{% extends 'blog/base.html' %}
{% load static %}

{% block msg  %}
  {% if messages  %}
  {% for message in messages %}
  <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show  my-3" {% endif %} >
       <strong>{{message}}</strong>
       <button type="button" class="close" data-dismiss="alert" aria-label="close">
       <span aria-hidden="true">&times;</span>
    </button>
  </div>

  {% endfor %}
  {% endif %}

{% endblock msg %}
{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
  <h4 class="my-5 ">Profile</h4> 
  <h5>{{full_name}}</h5>
  {% for  group in groups %}          
    <p>{{group.name}}</p>
  {% endfor %}
</div>
{% endblock side %}
{% block content %}
 <div class="col-sm-10">
    <h3 class="text-white my-5">Dashborad Page </h3>

     <a href="{% url 'addpost' %}" class="btn btn-success">Add Post</a>
    <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
     {% if posts %}
     <table class="table table-hover bg-white">
         <thead>
             <tr class="text-center">
                 <th scope="col" style="width:2;">ID</th>
                 <th scope="col" style="width:28;">Title</th>
                 <th scope="col" style="width:55;">Description</th>
                 <th scope="col" style="width:15;">Actions</th>
                
             </tr>
         </thead>
         <tbody>
             {% for post in posts %}
                <tr>
                 <th scope="row">{{post.id}}</th>
                 <td>{{post.title}}</td>
                 <td>{{post.desc}}</td>
                 <td class="text-center"> 
                 <a href="{% url 'updatepost' post.id %}" class="btn btn-warning btn-sm">Edit</a>
                 <br> <br>
                 {% if perms.blog.delete_post %}
                  <form action="{% url 'deletepost' post.id %}" method="post" class="d-inline">
                       {% csrf_token %}
                  <input type="submit" class="btn btn-danger btn-sm" value="delete"> 
                  </form>
                  {% endif %}
                  </td>
                </tr>
             {% endfor %}
         </tbody>
     </table>
     {% else %}
       <h4 class="text-center alert alert-warning">No Records</h4>
     {% endif %}
 </div>
 
{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
      
<div class="col-sm-10">
    <h3 class="text-white my-5">Home Page</h3>
    {%  for posts in posts %}
    <div class="jumbotron jumbotron-fluid jumbo-color">
     <div class="container">
         <h1 class="display-4 font-weight-bold">{{posts.title}}</h1>
         <p class="lead">{{posts.desc}}</p>
     </div>
    </div>
    {%  endfor %}
</div>

{% endblock content %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
 
    
<div class="col-sm-10">
    <h3 class="text-white my-5">Login Page</h3>
    <form action=""  method="post"  novalidate>
     {% csrf_token %}
     {% for fm in form %}
        <div class="form-group">
          {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
        </div>
      {% endfor %}
      <input type="submit" value="Login" class="btn btn-primary">
      {% if form.non_field_errors %}
        {%  for error in form.non_field_errors %}
           <p  class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
      {% endif%}
    </form>
</div>
{% endblock content %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">MiniBlog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
          {%  if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashborad' %}">Dashborad</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        
        
        
        </ul>
      </div>
    </div>
  </nav>

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
 
<div class="col-sm-10">
    <h3 class="text-white my-5">Become An Author</h3>
    {% if messages %}
    {% for message in messages %}
     <p {% if message.tags%} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
    {% endfor %}
    {% endif %}
 <form action=""  method="post" novalidate>
   {% csrf_token %}
   {% for fm in form %}
   <div class="form-group">
     {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
    </div>
   {% endfor %}
   <input type="submit" value="Submit" class="btn btn-primary">
    {% if form.non_field_errors %}
     {%  for error   in form.non_field_errors %}
      <p  class="alert alert-danger my-3">{{error}}</p>
     {% endfor %}
    {% endif%}
 </form>
</div>
{% endblock content %}

blog/templates/blog/updatepost.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
 <div class="col-sm-10"> 
     
    {% if messages %}
    {% for message in messages %}
     <p {% if message.tags%} class="alert alert-{{message.tags}} my-5" {% endif %}>{{message}}</p>
    {% endfor %}
    {% endif %}

   <h1 class="text-white my-5">Dashborad/ Update Post</h1>
   <form action="" method="post" novalidate>
       {% csrf_token %}
       {{form.as_p}}
       <input type="submit" value="update" class="btn btn-success">
       <a href="{% url 'dashborad' %}" class="btn btn-danger">Cancel</a>
   </form>
 </div>

{% endblock content %}